routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Middleware\AdminOrSuperAdmin;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/counter', 'AppController@counter');

Route::group(['middleware' => ['setLocale']], function ($router) {
	Route::get('/', 'HomeController@index');

	Auth::routes(['verify' => true]);
});

Route::group(['middleware' => ['auth', 'verified', 'completed', 'setLocale', 'xss_protection']], function ($router) {

	Route::get('/logout', 'Auth\LoginController@logout');

	Route::get('/dashboard', 'DashboardController@index')->name('dashboard')->withoutMiddleware(['completed']);

	Route::match(['get', 'post'], '/user/profile', 'UserController@profile')->name('user_profile')->withoutMiddleware(['completed']);

	Route::group(['middleware' => ['permission:manage sales']], function () {
		Route::resource('credit-notes', 'CreditNoteController');
		Route::get('credit-notes/{credit_note}/pdf', 'CreditNoteController@pdf')->name('credit-notes.pdf');
		Route::get('credit-notes/{credit_note}/print', 'CreditNoteController@print')->name('credit-notes.print');
		Route::post('credit-notes/{credit_note}/mail', 'CreditNoteController@mail')->name('credit-notes.mail');

		Route::resource('estimates', 'EstimateController');
		/* Route::resource('remissions', 'RemissionController'); */
		Route::get('estimates/{estimate}/pdf', 'EstimateController@pdf')->name('estimates.pdf');
		Route::get('estimates/{estimate}/print', 'EstimateController@print')->name('estimates.print');
		Route::post('estimates/{estimate}/mail', 'EstimateController@mail')->name('estimates.mail');
		Route::prefix('pos')->group(function () {
			Route::get('/', 'PosController@index')->name('pos.index');
			Route::post('/order/create/{mode?}', 'PosController@createOrder')->where('mode', 'online|offline')->name('pos.createOrder');
		});
		Route::post('estimates/{estimate}/approve', 'EstimateController@getClone')->name('estimates.approve');
		Route::resource('remissions', 'RemissionController');
	});

	Route::group(['middleware' => ['permission:manage expenses']], function () {
		Route::resource('debit-notes', 'DebitNoteController');
		Route::resource('purchase-orders', 'PurchaseOrderController');
		Route::resource('ncfs', 'NcfController');
	});

	/* invoices and transaction related routes*/
	Route::group(['middleware' => ['redirect_for_invoices']], function () {
		Route::get('invoices', function() {
			return redirect()->route('invoices.index', ['type' => 'sale']);
		});
		Route::get('invoices/create/{type}', 'InvoiceController@create')->where('type', 'sale|recurring|supplier')->name('invoices.create');
		Route::post('invoices/{type}', 'InvoiceController@store')->where('type', 'sale|recurring|supplier')->name('invoices.store');
		Route::get('invoices/{type}', 'InvoiceController@index')->where('type', 'sale|recurring|supplier')->name('invoices.index');
		Route::post('invoices/{invoice}/void', 'InvoiceController@void')->name('invoices.void');

		Route::resource('invoices', 'InvoiceController')->except([
		    'create', 'store', 'index'
		]);

		Route::get('invoices/{invoice}/pdf', 'InvoiceController@pdf')->name('invoices.pdf');
		Route::get('invoices/{invoice}/print', 'InvoiceController@print')->name('invoices.print');
		Route::get('invoices/{invoice}/print/template/{template_no}/{view}', 'InvoiceController@printWithTemplate');
		Route::post('invoices/{invoice}/mail', 'InvoiceController@mail')->name('invoices.mail');
	});

	Route::group(['middleware' => ['redirect_for_transactions']], function () {
		Route::get('transactions', function() {
			return redirect()->route('transactions.index', ['type' => 'in']);
		});
		
		Route::get('transactions/{type}', 'TransactionController@index')->where('type', 'in|out|recurring')->name('transactions.index');
		Route::get('transactions/create/{type}', 'TransactionController@create')->where('type', 'in|out|recurring')->name('transactions.create');
		Route::post('transactions/{type}', 'TransactionController@store')->where('type', 'in|out|recurring')->name('transactions.store');

		Route::resource('transactions', 'TransactionController')->except([
		    'create', 'store', 'index'
		]);
		Route::get('transactions/{transaction}/print', 'TransactionController@print')->name('transactions.print');
	});

	Route::group(['middleware' => ['permission:manage contacts']], function () {
		Route::resource('clients', 'ClientController');
		Route::resource('suppliers', 'SupplierController');
	});
		
	Route::group(['middleware' => ['permission:manage inventories']], function () {
		Route::resource('taxes', 'TaxController')->except([
		    'show'
		]);
		Route::get('taxes/{tax}', function() {
			return redirect()->route('taxes.index');
		});
		Route::resource('item-categories', 'ItemCategoryController')->except([
		    'show'
		]);
		Route::get('item-categories/{item_category}', function() {
			return redirect()->route('item-categories.index');
		});
		Route::any('inventories/search', 'InventoryController@search')->name('inventories.search')->withoutMiddleware(['permission:manage inventories']);
		Route::resource('inventories', 'InventoryController');
		Route::resource('inventory-adjustments', 'InventoryAdjustmentController');
	});

	Route::middleware([AdminOrSuperAdmin::class])->group(function () {
		Route::get('/settings/user', 'UserController@edit')->name('users.edit');
		Route::post('/settings/user', 'UserController@update')->name('users.update');
		Route::get('/settings/company', 'UserController@company')->name('company.edit');
		Route::post('/settings/company', 'UserController@companyUpdate')->name('company.update');
		Route::resource('employees', 'EmployeeController');
		Route::resource('departments', 'DepartmentController');
		Route::resource('designations', 'DesignationController');
		Route::resource('insurance-brands', 'InsuranceBrandController');
		Route::resource('leave-types', 'LeaveTypeController');
		Route::resource('leave-applications', 'LeaveApplicationController');
		Route::get('leave-reports', 'LeaveReportController@index')->name('leave-reports.index');
		Route::get('summary-report', 'LeaveReportController@summary')->name('summary-report.summary');
		Route::get('my-leave-report', 'LeaveReportController@my_leave_report')->name('my-leave-report.my-leave');
		Route::get('requested-applications', 'LeaveApplicationController@requested_applications')->name('requested-applications.requested');

		Route::resource('benefits', 'BenefitController');
		Route::resource('with-holdings', 'WithHoldingController');
		Route::resource('discounts', 'DiscountController');
		Route::resource('extra-hours', 'ExtraHourController');
		Route::resource('payroll-reports', 'PayrollReportController');

		Route::resource('roles', 'RoleController')->except([
		    'show'
		]);
		Route::get('roles/{role}', function() {
			return redirect()->route('roles.index');
		});

		Route::resource('memberships', 'MembershipController');

		/* Route::resource('leaves', 'LeaveController'); */

		Route::resource('leaves', 'LeaveController', ['parameters' => [
    		'leaves' => 'leave'
		]]);

		Route::post('/paid', 'PayrollReportController@paid')->name('employees.paid');
	});

	Route::prefix('user-management')->middleware([AdminOrSuperAdmin::class])->group(function () {
		 Route::get('users', 'UserManagementController@users')->name('user-management.users');
		Route::resource('users', 'UserManagementController')->except([
		    'index',
		    'show',
		])->names([
		    'create' => 'user-management.users.create',
		    'store' => 'user-management.users.store',
		    'edit' => 'user-management.users.edit',
		    'update' => 'user-management.users.update',
		    'destroy' => 'user-management.users.destroy'
		])->parameters([
		    'users' => 'company_user'
		]); 

		/*Route::resource('roles', 'RoleController')->except([
		    'show'
		])->names([
		    'index' => 'user-management.roles.create',
		    'create' => 'user-management.roles.create',
		    'store' => 'user-management.roles.store',
		    'edit' => 'user-management.roles.edit',
		    'update' => 'user-management.roles.update',
		    'destroy' => 'user-management.roles.destroy'
		]);*/
		

		// Route::get('roles', 'UserManagementController@roles')->name('user-management.roles');
		// Route::match(['get', 'post'], 'roles/create', 'UserManagementController@createRole')->name('user-management.roles.create');
		// Route::get('roles/{role}', 'UserManagementController@editRole')->name('user-management.roles.edit');
		// Route::put('roles/{role}/update', 'UserManagementController@assignPermissionsToRole')->name('user-management.roles.update');
	});

	Route::group(['middleware' => ['permission:manage inventories|manage contacts']], function () {
		Route::get('/import/{resource}', 'ImportController@showForm')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_resource');
		Route::post('/import/{resource}', 'ImportController@processImport')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_process');

		Route::get('/export/{resource}', 'ExportController@export')->where('resource', 'clients|suppliers|inventories|item-categories')->name('export_resource');
	});

	Route::prefix('app')->group(function () {
	    Route::post('generate-item-row', 'AppController@generateItemRow');
	    Route::post('generate-concept-row', 'AppController@generateConceptRow');
	    Route::post('contact-invoices-row', 'AppController@getContactInvoicesRows');
	    Route::post('contact-credit-notes', 'AppController@getContactCreditNotes');
	    Route::post('contact-debit-notes', 'AppController@getContactDebitNotes');

app/Http/Controllers/Api/TransactionController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Validators\TransactionValidator;

use App\Http\Resources\Transaction as TransactionResource;
use App\Http\Resources\TransactionCollection;

use App\Transaction;
use App\Supplier;
use App\Client;
use App\Item;
use App\Invoice;
use App\ConceptItem;
use App\Tax;

use Illuminate\Support\Facades\Mail;
use App\Mail\TransactionCreated;
use App\Events\PaymentCreatedOrUpdated;

use App\Services\TransactionService;
use App\Exceptions\ServiceException;

use DB;
use Auth;
use Config;
use Image;
use File;
use Cache;
use PDF;

use App\Traits\ApiResponse;

class TransactionController extends Controller
{
    use ApiResponse;

    protected $transactionService;

    public function __construct(TransactionService $transactionService)
    {
        $this->authorizeResource(Transaction::class, 'transaction');
        $this->transactionService = $transactionService;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request, $type)
    {
        $user = $request->user();
        $transactions = $user->company->transactions->where('type', $type)->values();

        $term = $request->input('term') ?? null;
        $perPage = $request->input('per_page') ?? 10;
        $page = $request->input('page') ?? 1;

        if ($term) {
            $transactions = $transactions->reject(function ($element) use ($term) {
                // search according to the data-tables.
                $searchCondition = 
                    mb_strpos(strtolower($element->receipt_number), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->voucher_number), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->detail_line), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->amount), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->bank_account), strtolower($term)) === false;

                if ($element->contact) {
                    $searchCondition = $searchCondition && mb_strpos(strtolower($element->contact->name), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->contact->phone), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->contact->tax_id), strtolower($term)) === false;
                }                   

                $searchCondition = $searchCondition && mb_strpos(strtolower($element->frequency), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->frequency_type), strtolower($term)) === false &&

                    mb_strpos(strtolower(dateFormat($element->start_date)), strtolower($term)) === false &&
                    mb_strpos(strtolower(dateFormat($element->end_date)), strtolower($term)) === false &&

                    mb_strpos(strtolower($element->annotation), strtolower($term)) === false &&
                    mb_strpos(strtolower($element->observation), strtolower($term)) === false;
                return $searchCondition;

            })->values();
        }

        // Why do this because it loads appends attribute.
        // which make recursive call.
        $transactions->each(function ($transaction, $key) {
            $transaction->setAppends([]);
            $transaction->unsetRelation('invoices')->unsetRelation('conceptItems');
        });

        $paginateData = $transactions->paginate($perPage);
        $collection = new TransactionCollection($paginateData->getCollection());
        $metaInfo = $paginateData->toArray();
        unset($metaInfo['data']);

        return $this->successResponse(['data' => $collection, 'meta' => $metaInfo]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, $type)
    {
        $transactionValidator = new TransactionValidator($type);
        $input = $request->all();

        if (!$transactionValidator->with($input)->passes()) {
            return $this->failResponse([
                "message" => $transactionValidator->getErrors()[0],
                "messages" => $transactionValidator->getErrors(),
            ], 422);
        }

        try {
            DB::beginTransaction();
            $transaction = $this->transactionService->store($request, $type);
            DB::commit();
            return $this->successResponse([
                'data' => new TransactionResource($transaction),
                'message' => trans('messages.transaction_created')
            ]);
        } catch (\Exception | ServiceException $e) {
            DB::rollback();
            return $this->failResponse([
                "message" => $e->getMessage(),
                "messages" => [$e->getMessage()],
            ], $e->getCode());
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function show(Transaction $transaction)
    {
        return $this->successResponse(['data' => new TransactionResource($transaction)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Transaction $transaction)
    {
        $type = $transaction->type;
        $input = $request->all();

        $transactionValidator = new TransactionValidator($transaction->type, 'update');
        if (!$transactionValidator->with($input)->passes()) {
            return $this->failResponse([
                "message" => $transactionValidator->getErrors()[0],
                "messages" => $transactionValidator->getErrors(),
            ], 422);
        }

        try {
            DB::beginTransaction();
            $transaction = $this->transactionService->update($request, $transaction);
            
            // prePrint(new TransactionResource($transaction));
            DB::commit();
            return $this->successResponse([
                'data' => new TransactionResource($transaction),
                'message' => trans('messages.transaction_updated')
            ]);
        } catch (\Exception | ServiceException $e) {
            DB::rollback();
            return $this->failResponse([
                "message" => $e->getMessage(),
                "messages" => [$e->getMessage()],
            ], $e->getCode());
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Transaction  $transaction
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, Transaction $transaction)
    {
        try {
            DB::beginTransaction();
            $this->transactionService->destroy($request, $transaction);
            DB::commit();
            return $this->successResponse([
                'message' => trans('messages.transaction_deleted')
            ]);
        } catch (\Exception | ServiceException $e) {
            DB::rollback();
            return $this->failResponse([
                "message" => $e->getMessage(),
                "messages" => [$e->getMessage()],
            ], $e->getCode());
        }
    }
}

resources/views/transactions/in/index.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.received_payments'))

@section('content')
<div class="dashboard-right cust-dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.received_payments') }}</h2>
        <div class="custom-tooltip"><span class="help-icon"><i class="fa fa-question-circle" aria-hidden="true"></i>
            </span>
            <span class="tooltiptext">{{ __('labels.if_you_need_help_creating').' '.__('labels.received_payment') }}</span>
        </div>
        <div class="invoice-btns invoice-btns-position">
            <div id="export-buttons" style="display: none;"></div>
            <a href="{{ route('transactions.create', ['type' => $type]) }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('labels.new_label').' '.__('labels.payment_received') }}</a>
        </div>
       
        <div class="tabs-custom">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="cal-filter-cnt cal-filter-cust-btns" id="dates-filters" style="display:none">
                        <span>{{ __('labels.from') }}: <input name="date-filter-min" id="date-filter-min" type="text" autocomplete="off"></span>
                        <span>{{ __('labels.to') }}: <input name="date-filter-max" id="date-filter-max" type="text" autocomplete="off"></span>
                    </div>
                    <div class="list-table-custom  products-table table-responsive">
                        <table class="table table-striped" id="transactions-received-list-table">
                            <thead>
                                <tr>
                                    <th>{{ __('labels.receipt_number') }}</th>
                                    <th>{{ __('labels.contact') }}</th>
                                    <th>{{ __('labels.details') }}</th>
                                    <th>{{ __('labels.creation_date') }}</th>
                                    <th>{{ __('labels.account') }}</th>
                                    <th>{{ __('labels.amount') }}</th>
                                    <th>{{ __('labels.annotation') }}</th>
                                    <th>{{ __('labels.actions') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                                @forelse ($transactions as $transaction)
                                <tr>
                                    <td>{{ $transaction->receipt_number }}</td>
                                    <td>{{ $transaction->contact ? $transaction->contact->name : 'N/A' }} </td>
                                    <td>{{ __('labels.invoice_number') }}: {{ $transaction->invoices->implode('id', ', ') }}</td>
                                    <td>{{ dateFormat($transaction->start_date) }}</td>
                                    <td>{{ $transaction->bankAccount ? $transaction->bankAccount->name : 'N/A' }}</td>
                                    @if($transaction->currency)
                                    <td>{{ moneyFormat($transaction->currency->symbol) }}</td>
                                    @else
                                    <td>{{ moneyFormat($transaction->amount) }}</td>
                                    @endif
                                    <td>{{ showIfAvailable($transaction->annotation) }}</td>
                                    <td class="to-show">
                                    <div class="inner-to-show">
                                        <i class="fa fa-sort-desc action-btn" class="dropdown-toggle" data-toggle="dropdown"></i>
                                        <div class="dropdown-menu">
                                            <ul>
                                                <li><a href="{{route('transactions.show', $transaction)}}">{{ __('labels.view') }}</a></li>
                                                <li><a href="{{route('transactions.edit', $transaction)}}">{{ __('labels.edit') }}</a></li>
                                                <li><a class="delete_resource" data-resource="{{ 'destroy-transaction-form-' . $transaction->id }}" href="{{route('transactions.destroy', $transaction)}}">{{ __('labels.delete') }}</a></li>
                                                {{ Form::open(array('method'=>'DELETE','route' => ['transactions.destroy', $transaction], 'id' => "destroy-transaction-form-{$transaction->id}", 'style' => 'display: none')) }}
                                                {!! Form::close() !!}
                                            </ul>
                                        </div>
                                    </div>
                                    </td>
                                </tr>
                                @empty
                                <tr class="no-data-row">
                                    <td colspan="9" rowspan="2" align="center">
                                        <div class="message"><p>{{ __('labels.you_have_not_yet_create_new').' '.__('labels.transaction') }}!</p></div>
                                        <div class="invoice-btns">
                                            <a href="{{ route('transactions.create', ['type' => $type]) }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('labels.new_label').' '.__('labels.payment_received') }}</a>
                                        </div>
                                    </td>
                                </tr>
                                @endforelse 
                            </tbody>
                            <tfoot>
                                <tr>
                                    <!-- <th>Number</th>
                                    <th>Contact</th>
                                    <th>Creation date</th>
                                    <th>Expiration date</th>
                                    <th>Total</th>
                                    <th>Paid</th>
                                    <th>Pending</th>
                                    <th>Status</th>
                                    <th>Actions</th> -->
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection