routes/web.php
		Route::get('invoices/{invoice}/print', 'InvoiceController@print')->name('invoices.print');
		Route::get('invoices/{invoice}/print/template/{template_no}/{view}', 'InvoiceController@printWithTemplate');
		Route::post('invoices/{invoice}/mail', 'InvoiceController@mail')->name('invoices.mail');
	});

	Route::group(['middleware' => ['redirect_for_transactions']], function () {
		Route::get('transactions', function() {
			return redirect()->route('transactions.index', ['type' => 'in']);
		});
		
		Route::get('transactions/{type}', 'TransactionController@index')->where('type', 'in|out|recurring')->name('transactions.index');
		Route::get('transactions/create/{type}', 'TransactionController@create')->where('type', 'in|out|recurring')->name('transactions.create');
		Route::post('transactions/{type}', 'TransactionController@store')->where('type', 'in|out|recurring')->name('transactions.store');

		Route::resource('transactions', 'TransactionController')->except([
		    'create', 'store', 'index'
		]);
		Route::get('transactions/{transaction}/print', 'TransactionController@print')->name('transactions.print');
	});

	Route::group(['middleware' => ['permission:manage contacts']], function () {
		Route::resource('clients', 'ClientController');
		Route::resource('suppliers', 'SupplierController');
	});
		
	Route::group(['middleware' => ['permission:manage inventories']], function () {
		Route::resource('taxes', 'TaxController')->except([
		    'show'
		]);
		Route::get('taxes/{tax}', function() {
			return redirect()->route('taxes.index');
		});
		Route::resource('item-categories', 'ItemCategoryController')->except([
		    'show'
		]);
		Route::get('item-categories/{item_category}', function() {
			return redirect()->route('item-categories.index');
		});
		Route::any('inventories/search', 'InventoryController@search')->name('inventories.search')->withoutMiddleware(['permission:manage inventories']);
		Route::resource('inventories', 'InventoryController');
		Route::resource('inventory-adjustments', 'InventoryAdjustmentController');
	});

	Route::middleware([AdminOrSuperAdmin::class])->group(function () {
		Route::get('/settings/user', 'UserController@edit')->name('users.edit');
		Route::post('/settings/user', 'UserController@update')->name('users.update');
		Route::get('/settings/company', 'UserController@company')->name('company.edit');
		Route::post('/settings/company', 'UserController@companyUpdate')->name('company.update');
		Route::resource('employees', 'EmployeeController');
		Route::resource('departments', 'DepartmentController');
		Route::resource('designations', 'DesignationController');
		Route::resource('insurance-brands', 'InsuranceBrandController');
		Route::resource('leave-types', 'LeaveTypeController');
		Route::resource('leave-applications', 'LeaveApplicationController');
		Route::get('leave-reports', 'LeaveReportController@index')->name('leave-reports.index');
		Route::get('summary-report', 'LeaveReportController@summary')->name('summary-report.summary');
		Route::get('my-leave-report', 'LeaveReportController@my_leave_report')->name('my-leave-report.my-leave');
		Route::get('requested-applications', 'LeaveApplicationController@requested_applications')->name('requested-applications.requested');

		Route::resource('benefits', 'BenefitController');
		Route::resource('with-holdings', 'WithHoldingController');
		Route::resource('discounts', 'DiscountController');
		Route::resource('extra-hours', 'ExtraHourController');
		Route::resource('payroll-reports', 'PayrollReportController');

		Route::resource('roles', 'RoleController')->except([
		    'show'
		]);
		Route::get('roles/{role}', function() {
			return redirect()->route('roles.index');
		});

		Route::resource('memberships', 'MembershipController');

		/* Route::resource('leaves', 'LeaveController'); */

		Route::resource('leaves', 'LeaveController', ['parameters' => [
    		'leaves' => 'leave'
		]]);

		Route::post('/paid', 'PayrollReportController@paid')->name('employees.paid');
	});

	Route::prefix('user-management')->middleware([AdminOrSuperAdmin::class])->group(function () {
		 Route::get('users', 'UserManagementController@users')->name('user-management.users');
		Route::resource('users', 'UserManagementController')->except([
		    'index',
		    'show',
		])->names([
		    'create' => 'user-management.users.create',
		    'store' => 'user-management.users.store',
		    'edit' => 'user-management.users.edit',
		    'update' => 'user-management.users.update',
		    'destroy' => 'user-management.users.destroy'
		])->parameters([
		    'users' => 'company_user'
		]); 

		/*Route::resource('roles', 'RoleController')->except([
		    'show'
		])->names([
		    'index' => 'user-management.roles.create',
		    'create' => 'user-management.roles.create',
		    'store' => 'user-management.roles.store',
		    'edit' => 'user-management.roles.edit',
		    'update' => 'user-management.roles.update',
		    'destroy' => 'user-management.roles.destroy'
		]);*/
		

		// Route::get('roles', 'UserManagementController@roles')->name('user-management.roles');
		// Route::match(['get', 'post'], 'roles/create', 'UserManagementController@createRole')->name('user-management.roles.create');
		// Route::get('roles/{role}', 'UserManagementController@editRole')->name('user-management.roles.edit');
		// Route::put('roles/{role}/update', 'UserManagementController@assignPermissionsToRole')->name('user-management.roles.update');
	});

	Route::group(['middleware' => ['permission:manage inventories|manage contacts']], function () {
		Route::get('/import/{resource}', 'ImportController@showForm')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_resource');
		Route::post('/import/{resource}', 'ImportController@processImport')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_process');

		Route::get('/export/{resource}', 'ExportController@export')->where('resource', 'clients|suppliers|inventories|item-categories')->name('export_resource');
	});

	Route::prefix('app')->group(function () {
	    Route::post('generate-item-row', 'AppController@generateItemRow');
	    Route::post('generate-concept-row', 'AppController@generateConceptRow');
	    Route::post('contact-invoices-row', 'AppController@getContactInvoicesRows');
	    Route::post('contact-credit-notes', 'AppController@getContactCreditNotes');
	    Route::post('contact-debit-notes', 'AppController@getContactDebitNotes');
	    // Route::post('set-locale', 'AppController@setLocale')->withoutMiddleware(['completed']);
	    Route::get('clear-cache', 'AppController@clearCache');
	    Route::get('coming-soon', 'AppController@comingSoon')->name('coming-soon');
		Route::get('contact-leave-balance', 'AppController@getContactLeaveBalance');
	    Route::post('generate-account-adjustment-row', 'AppController@generateAccountAdjustmentRow');
	    Route::post('generate-depr-item-row', 'AppController@generateDeprItemRow');
	    Route::get('get-depreciation-timeline', 'AppController@getDepreciationTimeline');
	});

	Route::get('generate-invoices-payments', 'AppController@generateInvoicesPayments');
	Route::post('documents/upload-files','DocumentController@uploadFiles');
	Route::post('documents/delete-file','DocumentController@deleteFile');
	Route::get('currency-exchange-rates', 'CurrencyExchangeRateController@index')->name('currency-exchange-rates.index');

	Route::resource('fixed-assets', 'FixedAssetController');

	Route::prefix('accounting')->group(function () {
		Route::resource('charts', 'UserAccountingHeadController', ['names' => [
		    'index' => 'accounting.charts'
		]])->except([
		    'show'
		]);
		Route::get('charts/generate-control-options/{chart}', 'UserAccountingHeadController@generateControlOptions')->name('accounting.generate-control-options');
		Route::resource('adjustments', 'AccountAdjustmentController')->names([
		    'index' => 'accounting.adjustments.index',
		    'create' => 'accounting.adjustments.create',
		    'store' => 'accounting.adjustments.store',
		    'show' => 'accounting.adjustments.show',
		    'edit' => 'accounting.adjustments.edit',
		    'update' => 'accounting.adjustments.update',
		    'destroy' => 'accounting.adjustments.destroy'
		])->parameters([
		    'adjustments' => 'account_adjustment'
		]);
		Route::get('journals', 'AccountingReportController@journals')->name('accounting.journals');
		Route::get('reports', 'AccountingReportController@index')->name('accounting.reports');
		Route::get('reports/balance-sheet', 'AccountingReportController@balanceSheet')->name('accounting.balance-sheet');
		Route::get('reports/income-statement', 'AccountingReportController@incomeStatement')->name('accounting.income-statement');
		Route::get('reports/general-ledger', 'AccountingReportController@generalLedgerReport')->name('accounting.general-ledger-report');
		Route::get('reports/journal-report', 'AccountingReportController@journals')->name('accounting.journal-report');
		// Route::post('charts/{user_accounting_head}', 'AccountingController@updateHead')->name('accounting.update-head');
	});
	Route::get('reports/general', 'AccountingReportController@generalReports')->name('accounting.general-reports');

});

Route::get('delete-user/{user}', 'UserController@deleteUser')->name('delete-user');
Route::post('app/set-locale', 'AppController@setLocale');


Route::group(['middleware' => ['setLocale']], function ($router) {
	// Localization
	Route::get('/js/lang.js', function () {
	    // $strings = Cache::rememberForever('lang.js', function () {
	        $lang = app()->getLocale();
	        $files = glob(resource_path('lang/' . $lang . '/*.php'));
	        $strings = [];
	        foreach ($files as $file) {
	            $name = basename($file, '.php');
	            if ($name !== "lang") {
	                $new_keys = require $file;
	                $strings = array_merge($strings, [$name => $new_keys]);
	            }
	        }
	    //     return $strings;
	    // });

app/Http/Controllers/DiscountController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Http\Response;
use Auth;
use DB;
use App\Discount;
use App\Validators\DiscountValidator;

use Config;

class DiscountController extends Controller
{
    public function __construct()
    {
        //$this->authorizeResource(Tax::class, 'tax');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = $request->user();
        $discounts = $user->company->discounts;
        if ($request->wantsJson() || $request->ajax()) {
            $jsonCollection = collect();
            $discounts->each(function ($item, $key) use ($jsonCollection) {
                $jsonCollection->push([
                    'sr_no' => $key + 1,
                    'employee' => $item->employee,
                    'type' => $item->type,
                    'start_date' => $item->start_date,
                    'end_date' => $item->end_date,
                    'frequency' => $item->frequency,
                    'frequency_type' => $item->frequency_type,
                    'observation' => $item->observation,
                    'amount' => $item->amount,
                    'id' => $item->id,
                ]);
            });
            return response()->json(['data' => $jsonCollection]);
        }
        return view('discounts.index', compact('discounts'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create(Request $request)
    {
        $user = $request->user();
        $employee_options = ['' => trans('labels.select_employee')] + $user->company->employees->pluck('name', 'id')->toArray();
        $type_option = ['' => trans('labels.select_type')] + $this->mapOptionsBasedOnLocale(Config::get('constants.discount_type_option'));
        $frequency_type_option = ['' => trans('labels.select_frequency_type')] + $this->mapOptionsBasedOnLocale(Config::get('constants.payroll_frequency_type_option'));
        $incomes_option = ['' => trans('labels.select_incomes_option')] + $this->mapOptionsBasedOnLocale(Config::get('constants.payroll_incomes_option'));
        return view('discounts.create', compact('employee_options', 'type_option', 'frequency_type_option', 'incomes_option'));
        return view('discounts.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, DiscountValidator $discountValidator)
    {
        try {
            DB::beginTransaction();
            $input = $request->all();

            if (!$discountValidator->with($input)->passes()) {
                $request->session()->flash('error', $discountValidator->getErrors()[0]);
                return back()
                    ->withErrors($discountValidator->getValidator())
                    ->withInput();
            }

            $user = $request->user();

            $data = [
                'employee_id' => $input['employee_id'],
                'type' => $input['type'],
                'start_date' => $input['start_date'],
                'end_date' => $input['end_date'],
                'observation' => $input['observation'],
                'recurring_type' => $input['recurring_type'],
                'frequency_type' => $input['frequency_type'],
                'frequency' => $input['frequency'],
                'amount' => $input['amount'],
                'incomes' => $input['incomes'],
                'user_id' => $user->id
            ];

            $discounts = $user->company->discounts()->create($data);

            DB::commit();

            $request->session()->flash('success', trans('messages.discount_created'));
            return redirect()->route('discounts.index');

        } catch (\Exception $e) {
            DB::rollback();
            $request->session()->flash('error', $e->getMessage());
            return back()->withInput();
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Benefit  $benefit
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, Discount $discount)
    {
        $user = $request->user();
        $employee_options = ['' => trans('labels.select_employee')] + $user->company->employees->pluck('name', 'id')->toArray();
        $type_option = ['' => trans('labels.select_type')] + $this->mapOptionsBasedOnLocale(Config::get('constants.discount_type_option'));
        $frequency_type_option = ['' => trans('labels.select_frequency_type')] + $this->mapOptionsBasedOnLocale(Config::get('constants.payroll_frequency_type_option'));
        $incomes_option = ['' => trans('labels.select_incomes_option')] + $this->mapOptionsBasedOnLocale(Config::get('constants.payroll_incomes_option'));
        return view('discounts.edit', compact('discount', 'employee_options', 'type_option', 'frequency_type_option', 'incomes_option'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Discount $discount, DiscountValidator $discountValidator)
    {
        try {
            DB::beginTransaction();
            $input = $request->all();
            
            if (!$discountValidator->with($input)->passes()) {
                $request->session()->flash('error', $discountValidator->getErrors()[0]);
                return back()
                    ->withErrors($discountValidator->getValidator())
                    ->withInput();
            }

            $user = $request->user();

            $data = [
                'employee_id' => $input['employee_id'],
                'type' => $input['type'],
                'start_date' => $input['start_date'],
                'end_date' => $input['end_date'],
                'observation' => $input['observation'],
                'recurring_type' => $input['recurring_type'],
                'frequency_type' => $input['frequency_type'],
                'frequency' => $input['frequency'],
                'amount' => $input['amount'],
                'incomes' => $input['incomes'],
                'user_id' => $user->id
            ];

            $discount->update($data);

            DB::commit();

            $request->session()->flash('success', trans('messages.discount_updated'));
            return redirect()->route('discounts.index');

        } catch (\Exception $e) {
            DB::rollback();
            $request->session()->flash('error', $e->getMessage());
            return back()->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Discount  $discount
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request,  Discount $discount)
    {
        try {
            $discount->delete();
            $request->session()->flash('success', trans('message.discount_deleted'));
            return redirect()->route('discounts.index');
        } catch (\Exception $e) {
            $request->session()->flash('error', $e->getMessage());
            return back()->withInput();
        } 
    }
}

resources/views/discounts/create.blade.php
@extends('layouts.dashboard')

@section('title', 'Discount')

@section('content')
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>New Discount</h2>
        <form method="POST" action="{{ route('discounts.store') }}" id="add-edit-discount-form">
            @csrf
            <div class="default-form add-new-contact-form">
                <div class="generate-invoice">
                    <div class="add-form row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">Employee <span>*</span></label>
                                {!! Form::select('employee_id', $employee_options, '', ['class'=>"form-control single-search-selection", 'id'=>"employee_id"]) !!}
                                @error('employee')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>                           
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">Types <span>*</span></label>
                                {!! Form::select('type', $type_option, '', ['class'=>"form-control single-search-selection", 'id'=>"type"]) !!}
                                @error('type')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>                        
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">Start Date <span>*</span></label>
                                 <input id="payroll_start_date" name="start_date" class="form-control"
                                required="required" value="{{old('payroll_start_date', '')}}"
                                autocomplete="off" />
                                @error('start_date')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>                        
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">End Date <span>*</span></label>
                                <input id="payroll_end_date" name="end_date" class="form-control"
                                required="required" value="{{old('end_date', '')}}"
                                autocomplete="off" />
                                @error('end_date')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>                        
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">Observations </label>
                                <textarea class="form-control" id="observations" name="observation">{{old('observation')}}</textarea>
                            </div>                        
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">Frequency <span>*</span></label>
                                <div class="wrap-two-cell-group">
                                    <div class="left">
                                        {!! Form::select('frequency_type', $frequency_type_option, '', ['class'=>"form-control col-5 single-search-selection", 'id'=>"frequency_type"]) !!}</div>
                                    <div class="right">
                                         <input type="text" class="form-control" name="frequency" id="frequency" value="{{old('frequency')}}">
                                    </div>
                                </div>
                            </div>  
                            
                            <div class="wrap-checkbox-block">
                                @if (old('_token') === null)
                                    <input type="radio" name="recurring_type" id="recurring" value="recurring" checked>
                                @else
                                <input type="radio" name="recurring_type" id="recurring" value="recurring" {{ old("recurring_type") == "recurring" ? "checked" : "" }} >
                                @endif
                                <label for="recurring">Recurring</label>
                                <input type="radio" name="recurring_type" id="on_time" value="on_time" {{ old("recurring_type") == "on_time" ? "checked" : "" }} >
                                <label for="on_time">On Time</label>
                            </div> 
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">Amount <span>*</span></label>
                                <input type="text" class="form-control" name="amount" id="contact" value="{{old('amount')}}">
                            </div>                        
                        </div>
                         <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">Incomes <span>*</span></label>
                                <div class="">
                                 {!! Form::select('incomes', $incomes_option, '', ['class'=>"form-control single-search-selection", 'id'=>"incomes"]) !!}
                                <div class="">
                                @error('incomes')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>                        
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments-section">
                    <div class="form-group popup-btns">
                        <a href="{{ route('discounts.index') }}"><button type="button" name="cancel" class="btn-custom cancel-btn">{{ __('labels.cancel') }}</button></a>
                        <button type="submit" name="submit" class="btn-custom">{{ __('labels.save') }}</button>
                    </div>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>
</div>
@endsection

resources/views/discounts/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Discount')

@section('content')
<div class="dashboard-right cust-dashboard-md-right cust-client-dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>Discounts</h2>
        <div class="custom-tooltip"><span class="help-icon"><i class="fa fa-question-circle" aria-hidden="true"></i>
            </span>
            <span class="tooltiptext">If you need help creating a Discount.</span>
        </div>
        <div class="invoice-btns invoice-btns-position">
            <div id="export-buttons" style=""><div class="dt-buttons"><button class="dt-button buttons-excel buttons-html5 btn-custom outline-btn" tabindex="0" aria-controls="invoice-list-table" type="button"><span>Export in excel</span></button> <button class="dt-button buttons-pdf buttons-html5 btn-custom outline-btn" tabindex="0" aria-controls="invoice-list-table" type="button"><span>Export in pdf</span></button> </div></div>
            <a href="{{ route('discounts.create') }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> New Discount</a>
        </div>
        <div class="tabs-custom">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="list-table-custom  products-table">
                        <table class="table table-striped" id="discounts-list-table">
                            <thead>
                                <tr>
                                    <th>Sr Number</th>
                                    <th>Employee</th>
                                    <th>Type</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Frequency</th>
                                    <th>Frequency Type</th>
                                    <th>Amount</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                               @forelse ($discounts as $key => $discount)
                                <tr>
                                    <!-- <td>{{ $discount->internal_number }}</td> -->
                                    <td>{{ $key+1 }}</td>
                                    <td>{{ $discount->employee->name }}</td>
                                    <td>{{ $discount->type }}</td>
                                    <td>{{ dateFormat($discount->start_date) }}</td>
                                    <td>{{ dateFormat($discount->end_date) }}</td>
                                    <td>{{ showIfAvailable($discount->frequency) }}</td>
                                    <td>{{ $discount->frequency_type }}</td>
                                    <td>{{ $discount->amount }}</td>
                                    <td class="to-show">
                                    <div class="inner-to-show">
                                        <i class="fa fa-sort-desc action-btn" class="dropdown-toggle" data-toggle="dropdown"></i>
                                        <div class="dropdown-menu">
                                            <ul>
                                                <li><a href="{{route('discounts.edit', $discount)}}">{{ __('labels.edit') }}</a></li>
                                                <li><a class="delete_resource" data-resource="{{ 'destroy-discount-form-' . $discount->id }}" href="{{route('discounts.destroy', $discount)}}">{{ __('labels.delete') }}</a></li>
                                                {{ Form::open(array('method'=>'DELETE','route' => ['discounts.destroy', $discount], 'id' => "destroy-discount-form-{$discount->id}", 'style' => 'display: none')) }}
                                                {!! Form::close() !!}
                                            </ul>
                                        </div>
                                    </div>
                                    </td>
                                </tr>
                                @empty
                                <tr class="no-data-row">
                                    <td colspan="7" rowspan="2" align="center">
                                        <div class="message"><p>{{ __('labels.you_have_not_yet_created').' '.__('labels.discount') }}!</p></div>
                                        <div class="invoice-btns">
                                            <a href="{{ route('discounts.create') }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('labels.new_label').' '.__('labels.discount') }}</a>
                                        </div>
                                    </td>
                                </tr>
                                @endforelse 
                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection