routes/web.php
		Route::get('credit-notes/{credit_note}/print', 'CreditNoteController@print')->name('credit-notes.print');
		Route::post('credit-notes/{credit_note}/mail', 'CreditNoteController@mail')->name('credit-notes.mail');

		Route::resource('estimates', 'EstimateController');
		/* Route::resource('remissions', 'RemissionController'); */
		Route::get('estimates/{estimate}/pdf', 'EstimateController@pdf')->name('estimates.pdf');
		Route::get('estimates/{estimate}/print', 'EstimateController@print')->name('estimates.print');
		Route::post('estimates/{estimate}/mail', 'EstimateController@mail')->name('estimates.mail');
		Route::prefix('pos')->group(function () {
			Route::get('/', 'PosController@index')->name('pos.index');
			Route::post('/order/create/{mode?}', 'PosController@createOrder')->where('mode', 'online|offline')->name('pos.createOrder');
		});
		Route::post('estimates/{estimate}/approve', 'EstimateController@getClone')->name('estimates.approve');
		Route::resource('remissions', 'RemissionController');
	});

	Route::group(['middleware' => ['permission:manage expenses']], function () {
		Route::resource('debit-notes', 'DebitNoteController');
		Route::resource('purchase-orders', 'PurchaseOrderController');
		Route::resource('ncfs', 'NcfController');
	});

	/* invoices and transaction related routes*/
	Route::group(['middleware' => ['redirect_for_invoices']], function () {
		Route::get('invoices', function() {
			return redirect()->route('invoices.index', ['type' => 'sale']);
		});
		Route::get('invoices/create/{type}', 'InvoiceController@create')->where('type', 'sale|recurring|supplier')->name('invoices.create');
		Route::post('invoices/{type}', 'InvoiceController@store')->where('type', 'sale|recurring|supplier')->name('invoices.store');
		Route::get('invoices/{type}', 'InvoiceController@index')->where('type', 'sale|recurring|supplier')->name('invoices.index');
		Route::post('invoices/{invoice}/void', 'InvoiceController@void')->name('invoices.void');

		Route::resource('invoices', 'InvoiceController')->except([
		    'create', 'store', 'index'
		]);

		Route::get('invoices/{invoice}/pdf', 'InvoiceController@pdf')->name('invoices.pdf');
		Route::get('invoices/{invoice}/print', 'InvoiceController@print')->name('invoices.print');
		Route::get('invoices/{invoice}/print/template/{template_no}/{view}', 'InvoiceController@printWithTemplate');
		Route::post('invoices/{invoice}/mail', 'InvoiceController@mail')->name('invoices.mail');
	});

	Route::group(['middleware' => ['redirect_for_transactions']], function () {
		Route::get('transactions', function() {
			return redirect()->route('transactions.index', ['type' => 'in']);
		});
		
		Route::get('transactions/{type}', 'TransactionController@index')->where('type', 'in|out|recurring')->name('transactions.index');
		Route::get('transactions/create/{type}', 'TransactionController@create')->where('type', 'in|out|recurring')->name('transactions.create');
		Route::post('transactions/{type}', 'TransactionController@store')->where('type', 'in|out|recurring')->name('transactions.store');

		Route::resource('transactions', 'TransactionController')->except([
		    'create', 'store', 'index'
		]);
		Route::get('transactions/{transaction}/print', 'TransactionController@print')->name('transactions.print');
	});

	Route::group(['middleware' => ['permission:manage contacts']], function () {
		Route::resource('clients', 'ClientController');
		Route::resource('suppliers', 'SupplierController');
	});
		
	Route::group(['middleware' => ['permission:manage inventories']], function () {
		Route::resource('taxes', 'TaxController')->except([
		    'show'
		]);
		Route::get('taxes/{tax}', function() {
			return redirect()->route('taxes.index');
		});
		Route::resource('item-categories', 'ItemCategoryController')->except([
		    'show'
		]);
		Route::get('item-categories/{item_category}', function() {
			return redirect()->route('item-categories.index');
		});
		Route::any('inventories/search', 'InventoryController@search')->name('inventories.search')->withoutMiddleware(['permission:manage inventories']);
		Route::resource('inventories', 'InventoryController');
		Route::resource('inventory-adjustments', 'InventoryAdjustmentController');
	});

	Route::middleware([AdminOrSuperAdmin::class])->group(function () {
		Route::get('/settings/user', 'UserController@edit')->name('users.edit');
		Route::post('/settings/user', 'UserController@update')->name('users.update');
		Route::get('/settings/company', 'UserController@company')->name('company.edit');
		Route::post('/settings/company', 'UserController@companyUpdate')->name('company.update');
		Route::resource('employees', 'EmployeeController');
		Route::resource('departments', 'DepartmentController');
		Route::resource('designations', 'DesignationController');
		Route::resource('insurance-brands', 'InsuranceBrandController');
		Route::resource('leave-types', 'LeaveTypeController');
		Route::resource('leave-applications', 'LeaveApplicationController');
		Route::get('leave-reports', 'LeaveReportController@index')->name('leave-reports.index');
		Route::get('summary-report', 'LeaveReportController@summary')->name('summary-report.summary');
		Route::get('my-leave-report', 'LeaveReportController@my_leave_report')->name('my-leave-report.my-leave');
		Route::get('requested-applications', 'LeaveApplicationController@requested_applications')->name('requested-applications.requested');

		Route::resource('benefits', 'BenefitController');
		Route::resource('with-holdings', 'WithHoldingController');
		Route::resource('discounts', 'DiscountController');
		Route::resource('extra-hours', 'ExtraHourController');
		Route::resource('payroll-reports', 'PayrollReportController');

		Route::resource('roles', 'RoleController')->except([
		    'show'
		]);
		Route::get('roles/{role}', function() {
			return redirect()->route('roles.index');
		});

		Route::resource('memberships', 'MembershipController');

		/* Route::resource('leaves', 'LeaveController'); */

		Route::resource('leaves', 'LeaveController', ['parameters' => [
    		'leaves' => 'leave'
		]]);

		Route::post('/paid', 'PayrollReportController@paid')->name('employees.paid');
	});

	Route::prefix('user-management')->middleware([AdminOrSuperAdmin::class])->group(function () {
		 Route::get('users', 'UserManagementController@users')->name('user-management.users');
		Route::resource('users', 'UserManagementController')->except([
		    'index',
		    'show',
		])->names([
		    'create' => 'user-management.users.create',
		    'store' => 'user-management.users.store',
		    'edit' => 'user-management.users.edit',
		    'update' => 'user-management.users.update',
		    'destroy' => 'user-management.users.destroy'
		])->parameters([
		    'users' => 'company_user'
		]); 

		/*Route::resource('roles', 'RoleController')->except([
		    'show'
		])->names([
		    'index' => 'user-management.roles.create',
		    'create' => 'user-management.roles.create',
		    'store' => 'user-management.roles.store',
		    'edit' => 'user-management.roles.edit',
		    'update' => 'user-management.roles.update',
		    'destroy' => 'user-management.roles.destroy'
		]);*/
		

		// Route::get('roles', 'UserManagementController@roles')->name('user-management.roles');
		// Route::match(['get', 'post'], 'roles/create', 'UserManagementController@createRole')->name('user-management.roles.create');
		// Route::get('roles/{role}', 'UserManagementController@editRole')->name('user-management.roles.edit');
		// Route::put('roles/{role}/update', 'UserManagementController@assignPermissionsToRole')->name('user-management.roles.update');
	});

	Route::group(['middleware' => ['permission:manage inventories|manage contacts']], function () {
		Route::get('/import/{resource}', 'ImportController@showForm')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_resource');
		Route::post('/import/{resource}', 'ImportController@processImport')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_process');

		Route::get('/export/{resource}', 'ExportController@export')->where('resource', 'clients|suppliers|inventories|item-categories')->name('export_resource');
	});

	Route::prefix('app')->group(function () {
	    Route::post('generate-item-row', 'AppController@generateItemRow');
	    Route::post('generate-concept-row', 'AppController@generateConceptRow');
	    Route::post('contact-invoices-row', 'AppController@getContactInvoicesRows');
	    Route::post('contact-credit-notes', 'AppController@getContactCreditNotes');
	    Route::post('contact-debit-notes', 'AppController@getContactDebitNotes');
	    // Route::post('set-locale', 'AppController@setLocale')->withoutMiddleware(['completed']);
	    Route::get('clear-cache', 'AppController@clearCache');
	    Route::get('coming-soon', 'AppController@comingSoon')->name('coming-soon');
		Route::get('contact-leave-balance', 'AppController@getContactLeaveBalance');
	    Route::post('generate-account-adjustment-row', 'AppController@generateAccountAdjustmentRow');
	    Route::post('generate-depr-item-row', 'AppController@generateDeprItemRow');
	    Route::get('get-depreciation-timeline', 'AppController@getDepreciationTimeline');
	});

	Route::get('generate-invoices-payments', 'AppController@generateInvoicesPayments');
	Route::post('documents/upload-files','DocumentController@uploadFiles');
	Route::post('documents/delete-file','DocumentController@deleteFile');
	Route::get('currency-exchange-rates', 'CurrencyExchangeRateController@index')->name('currency-exchange-rates.index');

	Route::resource('fixed-assets', 'FixedAssetController');

	Route::prefix('accounting')->group(function () {
		Route::resource('charts', 'UserAccountingHeadController', ['names' => [
		    'index' => 'accounting.charts'
		]])->except([
		    'show'
		]);
		Route::get('charts/generate-control-options/{chart}', 'UserAccountingHeadController@generateControlOptions')->name('accounting.generate-control-options');

app/Http/Controllers/Api/Client/CreditNoteController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Traits\ApiResponse;
use App\Transformers\DebitCreditNoteTransformer;
use DB;
use Auth;

class CreditNoteController extends Controller
{
	use ApiResponse;

    /**
     * listing of all credit notes
     * 
     * @OA\Get(
     *     path="/api/v1/clients/credit-notes",
     *     tags={"Credit Notes"},
     *     operationId="creditnotes",
     *     security={
     *          {"passport": {}},
     *      },
     *     @OA\Parameter(
     *         name="X-localization",
     *         in="header",
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="ok",
     *         content={
     *             @OA\MediaType(
     *                 mediaType="application/json",
     *             )
     *         }	
     *     )
     * )
     */

    public function index(Request $request)
    {
    	try{
    		$client = $request->user()->getClientInfo();
    		$creditNotes = $client->creditNotes;
    		$response = (new DebitCreditNoteTransformer())->transform($creditNotes);
    		if($response){
    			return $this->successResponse([
    				"message" => trans('messages.data_fetched'),
    				"data" => $response
    			]);
    		}else{
    			return $this->failResponse([
    				"message" => trans('messages.no_result_found'),
    			], 200);
    		}
    	} catch (\Exception $e) {
    		return $this->failResponse([
    			"message" => $e->getMessage(),
    		], 200);
    	}
    }
}

app/Http/Controllers/Api/Client/DebitNoteController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Traits\ApiResponse;
use App\Transformers\DebitCreditNoteTransformer;

use DB;
use Auth;

class DebitNoteController extends Controller
{
	use ApiResponse;

    /**
     * listing of all debit notes
     * 
     * @OA\Get(
     *     path="/api/v1/clients/debit-notes",
     *     tags={"Debit Notes"},
     *     operationId="debitnotes",
     *     security={
     *          {"passport": {}},
     *      },
     *     @OA\Parameter(
     *         name="X-localization",
     *         in="header",
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="ok",
     *         content={
     *             @OA\MediaType(
     *                 mediaType="application/json",
     *             )
     *         }
     *     )
     * )
     */
    
    public function index(Request $request)
    {
    	try{
    		$client = $request->user()->getClientInfo();
    		$debitNotes = (new DebitCreditNoteTransformer())->transform($client->debitNotes);
    		if($debitNotes){
    			return $this->successResponse([
    				"message" => trans('messages.data_fetched'),
    				"data" => $debitNotes
    			]);
    		}else{
    			return $this->failResponse([
    				"message" => trans('messages.no_result_found'),
    			], 200);
    		}
    	} catch (\Exception $e) {
    		return $this->failResponse([
    			"message" => $e->getMessage(),
    		], 200);
    	}
    }
}

app/Http/Controllers/Api/Client/EstimateController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Traits\ApiResponse;
use App\Transformers\EstimateTransformer;
use DB;
use Auth;

class EstimateController extends Controller
{
	use ApiResponse;

    /**
     * listing of all estimates
     * 
     * @OA\Get(
     *     path="/api/v1/clients/estimates",
     *     tags={"Estimates"},
     *     operationId="estimates",
     *     security={
     *          {"passport": {}},
     *      },
     *     @OA\Parameter(
     *         name="X-localization",
     *         in="header",
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="ok",
     *         content={
     *             @OA\MediaType(
     *                 mediaType="application/json",
     *             )
     *         }	
     *     )
     * )
     */
    
    public function index(Request $request)
    {
    	try{
    		$client = $request->user()->getClientInfo();
    		$estimates = (new EstimateTransformer())->transform($client->estimates);
    		if($estimates){
    			return $this->successResponse([
    				"message" => trans('messages.data_fetched'),
    				"data" => $estimates
    			]);
    		}else{
    			return $this->failResponse([
    				"message" => trans('messages.no_result_found'),
    			], 200);
    		}
    	} catch (\Exception $e) {
    		return $this->failResponse([
    			"message" => $e->getMessage(),
    		], 200);
    	}
    }
}

app/Http/Controllers/Api/Client/PaymentController.php
<?php

namespace App\Http\Controllers\Api\Client;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Validators\User\ProfileValidator;
use App\Validators\ClientValidator;
use App\Traits\ApiResponse;

use App\Transformers\PaymentTransformer;

use App\User;
use App\Company;
use App\Client;
use App\Transaction;

use DB;
use Auth;
use Config;
use Image;
use Cache;
use PDF;

class PaymentController extends Controller
{
	use ApiResponse;

    /**
     * listing of all payments
     * 
     * @OA\Get(
     *     path="/api/v1/clients/payments",
     *     tags={"Payments"},
     *     operationId="payments",
     *     security={
     *          {"passport": {}},
     *      },
     *     @OA\Parameter(
     *         name="X-localization",
     *         in="header",
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="ok",
     *     )
     * )
     */
    public function index(Request $request)
    { 
    	try {
    		$client = $request->user()->getClientInfo();
    		$transactions = (new PaymentTransformer())->transform($client->transactions);
    		if ($transactions) {
    			return $this->successResponse([
    				"message" => trans('messages.data_fetched'),
    				"data" => $transactions
    			]);
    		}else{
    			return $this->failResponse([
    				"message" => trans('messages.no_result_found'),
    			], 200);
    		}
    	} catch (\Exception $e) {
    		return $this->failResponse([
    			"message" => $e->getMessage(),
    		], 200);
    	}
    }

    /**
     * Get single payment detail
     * 
     * @OA\Get(
     *     path="/api/v1/clients/payments/{payment_id}",
     *     tags={"Payments"},
     *     operationId="singlePayments",
     *     security={
     *          {"passport": {}},
     *      },
     *     @OA\Parameter(
     *         name="X-localization",
     *         in="header",
     *     ),
     *     @OA\Parameter(
     *         name="payment_id",
     *         in="path",
     *     ),
     *     @OA\Response(
     *         response=200,
     *         description="ok",
     *         content={
     *             @OA\MediaType(
     *                 mediaType="application/json",
     *             )
     *         }
     *     )
     * )
     */
    public function show(Request $request, Transaction $transaction)
    {
        if (!$request->user()->can('view', [Transaction::class, $transaction] )) {
            return $this->failResponse([
                "message" => trans('messages.account_access')
            ], 200);
        }
        
    	try {
    		$transactions = (new PaymentTransformer())->singleTransform($transaction);
    		return $this->successResponse([
    			"message" => trans('messages.data_fetched'),
    			"data" => $transactions
    		]);
    	} catch (\Exception $e) {
    		return $this->failResponse([
    			"message" => $e->getMessage(),
    		], 200);
    	}
    }

}

resources/views/clients/index.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.clients'))

@section('content')
<div class="dashboard-right cust-dashboard-md-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.clients') }}</h2>
        <div class="custom-tooltip"><span class="help-icon"><i class="fa fa-question-circle" aria-hidden="true"></i>
            </span>
            <span class="tooltiptext">{{ __('labels.if_you_need_help_creating').' '.__('labels.client') }}</span>
        </div>
        <div class="invoice-btns invoice-btns-position">
            <a href="{{ route('import_resource', ['resource' => 'clients']) }}" class="btn-custom outline-btn"><i class="fa fa-upload" aria-hidden="true"></i> {{ __('labels.import_from_excel') }}</a>
            <a href="{{ route('export_resource', ['resource' => 'clients']) }}" class="btn-custom outline-btn"><i class="fa fa-download" aria-hidden="true"></i> {{ __('labels.export_clients') }}</a>
            <a href="{{ route('clients.create') }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('labels.new_client') }}</a>
        </div>
        <div class="tabs-custom">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="list-table-custom  products-table">
                        <table class="table table-striped" id="clients-list-table">
                            <thead>
                                <tr>
                                    <th>{{ __('labels.name') }}</th>
                                    <th>{{ __('labels.email') }}</th>
                                    <th>{{ __('labels.tax_id') }}</th>
                                    <th>{{ __('labels.phone') }}</th>
                                    <th>{{ __('labels.actions') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                            @forelse ($clients as $client)
                                <tr>
                                    <td>{{ $client->name }}</td>
                                    <td>{{ $client->email }}</td>
                                    <td>{{ showIfAvailable($client->tax_id) }}</td>
                                    <td>{{ showIfAvailable($client->phone) }}</td>
                                    <td class="to-show">
                                        <div class="inner-to-show">
                                            <i class="fa fa-sort-desc action-btn" class="dropdown-toggle" data-toggle="dropdown"></i>
                                            <div class="dropdown-menu">
                                                <ul>
                                                    <li><a href="{{route('clients.show', $client)}}">{{ __('labels.view') }}</a></li>
                                                    <li><a href="{{route('clients.edit', $client)}}">{{ __('labels.edit') }}</a></li>
                                                    <li><a class="delete_resource" data-resource="{{ 'destroy-client-form-' . $client->id }}" href="{{route('clients.destroy', $client)}}">{{ __('labels.delete') }}</a></li>
                                                    {{ Form::open(array('method'=>'DELETE','route' => ['clients.destroy', $client], 'id' => "destroy-client-form-{$client->id}", 'style' => 'display: none')) }}
                                                    {!! Form::close() !!}
                                                </ul>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @empty
                            <tr class="no-data-row">
                                <td colspan="5" rowspan="2" align="center">
                                    <div class="message"><p>{{ __('labels.you_have_not_yet_create_new').' '.__('labels.client') }}!</p></div>
                                    <div class="invoice-btns">
                                        <a href="{{ route('clients.create') }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('labels.new_client') }}</a>
                                    </div>
                                </td>
                            </tr>
                            @endforelse                                
                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection

resources/views/clients/show.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.show').' '.trans('labels.client'))

@section('content')
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container user-invoice-view-details">
        <a class="arrow-back d-block" href="{{ route('clients.index') }}">{{ __('labels.back') }}</a>
        <h2>{{ titleCase($client->name) }} Details</h2>
        <div class="default-form view-form-detail">
            <div class="generate-invoice">
                <div class="add-form row">
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="number"><b>{{ __('labels.identification_type') }}:</b></label>
                        <span class="value-form">{{ $client->identificationInfo ? showIfAvailable($client->identificationInfo->name) : 'N/A' }}</span>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="taxid"><b>{{ __('labels.tax_id') }}: </b></label>
                        <span class="value-form">{{ showIfAvailable($client->tax_id) }}</span>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="name"><b>{{ __('labels.name') }}: </b></label>
                        <span class="value-form">{{ showIfAvailable($client->name) }}</span>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                        <label for="email"><b>{{ __('labels.email') }}: </b></label>
                        <span class="value-form">{{ showIfAvailable($client->email) }}</span>
                    </div>
                    <div class="form-group col-sm-12 col-md-6">
                     <fieldset>
                        <label><b>{{ __('labels.address') }}: </b></label>
                        <span class="value-form">{{ addressFormat($client->address) }}</span>
                    </fieldset>
                </div>

                <div class="form-group col-sm-12 col-md-6">
                    <label for="department"><b>{{ __('labels.department') }}: </b></label>
                    <span class="value-form">{{ $client->sector ? showIfAvailable($client->sector->name) : 'N/A' }}</span>
                </div>
                <div class="form-group col-sm-12 col-md-6">
                    <label for="zip"><b>{{ __('labels.zip_code') }}: </b></label>
                    <span class="value-form">{{ $client->address ? showIfAvailable($client->address->zip) : 'N/A'  }}</span>
                </div>
                <div class="form-group col-sm-12 col-md-6">
                    <label for="mobile"><b>{{ __('labels.mobile') }}: </b></label>
                    <span class="value-form">{{ showIfAvailable($client->mobile) }}</span>
                </div>
                <div class="form-group col-sm-12 col-md-6">
                    <label for="phone"><b>{{ __('labels.phone') }}: </b></label>
                    <span class="value-form">{{ showIfAvailable($client->phone) }}</span>
                </div>
            </div>
            
        </div>
        <div class="tabs-custom default-form view-table-info">
            <ul class="nav nav-tabs">
                <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#client-points">{{ __('labels.points') }}</a></li>
            </ul>
            <div class="tab-content">
                <div id="client-points" class="tab-pane generate-invoice fade in active show">
                    <div class="add-form">                           
                        <div class="default-table">
                            <div class="list-table-custom">
                                <table class="table table-striped">
                                    <thead>
                                        <th>{{ __('labels.date') }}</th>
                                        <th>{{ __('labels.invoice') }}</th>
                                        <th>{{ __('labels.points') }}</th>
                                        <th>{{ __('labels.point_percentage') }}</th>
                                    </thead>
                                    @forelse($client->points as $clientPoint)
                                    <tr>
                                        <td>{{dateFormat($clientPoint->created_at)}}</td>
                                        <td><a href="{{route('invoices.show', $clientPoint->invoice) }}">{{ __('labels.invoice') }} #{{ $clientPoint->invoice->internal_number }}</a></td>
                                        <td>{{ showIfAvailable($clientPoint->points) }}</td>
                                        <td>{{ showIfAvailable($clientPoint->point_percentage) }}</td>
                                    </tr>
                                    @empty
                                    <tr class="empty-row">
                                        <td colspan="5"><p>{{ __('messages.client_has_not_points') }}</p></td>
                                    </tr>
                                    @endforelse
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>
<div class="clearfix"></div>
</div>
@endsection