routes/web.php
		Route::get('estimates/{estimate}/print', 'EstimateController@print')->name('estimates.print');
		Route::post('estimates/{estimate}/mail', 'EstimateController@mail')->name('estimates.mail');
		Route::prefix('pos')->group(function () {
			Route::get('/', 'PosController@index')->name('pos.index');
			Route::post('/order/create/{mode?}', 'PosController@createOrder')->where('mode', 'online|offline')->name('pos.createOrder');
		});
		Route::post('estimates/{estimate}/approve', 'EstimateController@getClone')->name('estimates.approve');
		Route::resource('remissions', 'RemissionController');
	});

	Route::group(['middleware' => ['permission:manage expenses']], function () {
		Route::resource('debit-notes', 'DebitNoteController');
		Route::resource('purchase-orders', 'PurchaseOrderController');
		Route::resource('ncfs', 'NcfController');
	});

	/* invoices and transaction related routes*/
	Route::group(['middleware' => ['redirect_for_invoices']], function () {
		Route::get('invoices', function() {
			return redirect()->route('invoices.index', ['type' => 'sale']);
		});
		Route::get('invoices/create/{type}', 'InvoiceController@create')->where('type', 'sale|recurring|supplier')->name('invoices.create');
		Route::post('invoices/{type}', 'InvoiceController@store')->where('type', 'sale|recurring|supplier')->name('invoices.store');
		Route::get('invoices/{type}', 'InvoiceController@index')->where('type', 'sale|recurring|supplier')->name('invoices.index');
		Route::post('invoices/{invoice}/void', 'InvoiceController@void')->name('invoices.void');

		Route::resource('invoices', 'InvoiceController')->except([
		    'create', 'store', 'index'
		]);

		Route::get('invoices/{invoice}/pdf', 'InvoiceController@pdf')->name('invoices.pdf');
		Route::get('invoices/{invoice}/print', 'InvoiceController@print')->name('invoices.print');
		Route::get('invoices/{invoice}/print/template/{template_no}/{view}', 'InvoiceController@printWithTemplate');
		Route::post('invoices/{invoice}/mail', 'InvoiceController@mail')->name('invoices.mail');
	});

	Route::group(['middleware' => ['redirect_for_transactions']], function () {
		Route::get('transactions', function() {
			return redirect()->route('transactions.index', ['type' => 'in']);
		});
		
		Route::get('transactions/{type}', 'TransactionController@index')->where('type', 'in|out|recurring')->name('transactions.index');
		Route::get('transactions/create/{type}', 'TransactionController@create')->where('type', 'in|out|recurring')->name('transactions.create');
		Route::post('transactions/{type}', 'TransactionController@store')->where('type', 'in|out|recurring')->name('transactions.store');

		Route::resource('transactions', 'TransactionController')->except([
		    'create', 'store', 'index'
		]);
		Route::get('transactions/{transaction}/print', 'TransactionController@print')->name('transactions.print');
	});

	Route::group(['middleware' => ['permission:manage contacts']], function () {
		Route::resource('clients', 'ClientController');
		Route::resource('suppliers', 'SupplierController');
	});
		
	Route::group(['middleware' => ['permission:manage inventories']], function () {
		Route::resource('taxes', 'TaxController')->except([
		    'show'
		]);
		Route::get('taxes/{tax}', function() {
			return redirect()->route('taxes.index');
		});
		Route::resource('item-categories', 'ItemCategoryController')->except([
		    'show'
		]);
		Route::get('item-categories/{item_category}', function() {
			return redirect()->route('item-categories.index');
		});
		Route::any('inventories/search', 'InventoryController@search')->name('inventories.search')->withoutMiddleware(['permission:manage inventories']);
		Route::resource('inventories', 'InventoryController');
		Route::resource('inventory-adjustments', 'InventoryAdjustmentController');
	});

	Route::middleware([AdminOrSuperAdmin::class])->group(function () {
		Route::get('/settings/user', 'UserController@edit')->name('users.edit');
		Route::post('/settings/user', 'UserController@update')->name('users.update');
		Route::get('/settings/company', 'UserController@company')->name('company.edit');
		Route::post('/settings/company', 'UserController@companyUpdate')->name('company.update');
		Route::resource('employees', 'EmployeeController');
		Route::resource('departments', 'DepartmentController');
		Route::resource('designations', 'DesignationController');
		Route::resource('insurance-brands', 'InsuranceBrandController');
		Route::resource('leave-types', 'LeaveTypeController');
		Route::resource('leave-applications', 'LeaveApplicationController');
		Route::get('leave-reports', 'LeaveReportController@index')->name('leave-reports.index');
		Route::get('summary-report', 'LeaveReportController@summary')->name('summary-report.summary');
		Route::get('my-leave-report', 'LeaveReportController@my_leave_report')->name('my-leave-report.my-leave');
		Route::get('requested-applications', 'LeaveApplicationController@requested_applications')->name('requested-applications.requested');

		Route::resource('benefits', 'BenefitController');
		Route::resource('with-holdings', 'WithHoldingController');
		Route::resource('discounts', 'DiscountController');
		Route::resource('extra-hours', 'ExtraHourController');
		Route::resource('payroll-reports', 'PayrollReportController');

		Route::resource('roles', 'RoleController')->except([
		    'show'
		]);
		Route::get('roles/{role}', function() {
			return redirect()->route('roles.index');
		});

		Route::resource('memberships', 'MembershipController');

		/* Route::resource('leaves', 'LeaveController'); */

		Route::resource('leaves', 'LeaveController', ['parameters' => [
    		'leaves' => 'leave'
		]]);

		Route::post('/paid', 'PayrollReportController@paid')->name('employees.paid');
	});

	Route::prefix('user-management')->middleware([AdminOrSuperAdmin::class])->group(function () {
		 Route::get('users', 'UserManagementController@users')->name('user-management.users');
		Route::resource('users', 'UserManagementController')->except([
		    'index',
		    'show',
		])->names([
		    'create' => 'user-management.users.create',
		    'store' => 'user-management.users.store',
		    'edit' => 'user-management.users.edit',
		    'update' => 'user-management.users.update',
		    'destroy' => 'user-management.users.destroy'
		])->parameters([
		    'users' => 'company_user'
		]); 

		/*Route::resource('roles', 'RoleController')->except([
		    'show'
		])->names([
		    'index' => 'user-management.roles.create',
		    'create' => 'user-management.roles.create',
		    'store' => 'user-management.roles.store',
		    'edit' => 'user-management.roles.edit',
		    'update' => 'user-management.roles.update',
		    'destroy' => 'user-management.roles.destroy'
		]);*/
		

		// Route::get('roles', 'UserManagementController@roles')->name('user-management.roles');
		// Route::match(['get', 'post'], 'roles/create', 'UserManagementController@createRole')->name('user-management.roles.create');
		// Route::get('roles/{role}', 'UserManagementController@editRole')->name('user-management.roles.edit');
		// Route::put('roles/{role}/update', 'UserManagementController@assignPermissionsToRole')->name('user-management.roles.update');
	});

	Route::group(['middleware' => ['permission:manage inventories|manage contacts']], function () {
		Route::get('/import/{resource}', 'ImportController@showForm')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_resource');
		Route::post('/import/{resource}', 'ImportController@processImport')->where('resource', 'clients|suppliers|inventories|item-categories')->name('import_process');

		Route::get('/export/{resource}', 'ExportController@export')->where('resource', 'clients|suppliers|inventories|item-categories')->name('export_resource');
	});

	Route::prefix('app')->group(function () {
	    Route::post('generate-item-row', 'AppController@generateItemRow');
	    Route::post('generate-concept-row', 'AppController@generateConceptRow');
	    Route::post('contact-invoices-row', 'AppController@getContactInvoicesRows');
	    Route::post('contact-credit-notes', 'AppController@getContactCreditNotes');
	    Route::post('contact-debit-notes', 'AppController@getContactDebitNotes');
	    // Route::post('set-locale', 'AppController@setLocale')->withoutMiddleware(['completed']);
	    Route::get('clear-cache', 'AppController@clearCache');
	    Route::get('coming-soon', 'AppController@comingSoon')->name('coming-soon');
		Route::get('contact-leave-balance', 'AppController@getContactLeaveBalance');
	    Route::post('generate-account-adjustment-row', 'AppController@generateAccountAdjustmentRow');
	    Route::post('generate-depr-item-row', 'AppController@generateDeprItemRow');
	    Route::get('get-depreciation-timeline', 'AppController@getDepreciationTimeline');
	});

	Route::get('generate-invoices-payments', 'AppController@generateInvoicesPayments');
	Route::post('documents/upload-files','DocumentController@uploadFiles');
	Route::post('documents/delete-file','DocumentController@deleteFile');
	Route::get('currency-exchange-rates', 'CurrencyExchangeRateController@index')->name('currency-exchange-rates.index');

	Route::resource('fixed-assets', 'FixedAssetController');

	Route::prefix('accounting')->group(function () {
		Route::resource('charts', 'UserAccountingHeadController', ['names' => [
		    'index' => 'accounting.charts'
		]])->except([
		    'show'
		]);
		Route::get('charts/generate-control-options/{chart}', 'UserAccountingHeadController@generateControlOptions')->name('accounting.generate-control-options');
		Route::resource('adjustments', 'AccountAdjustmentController')->names([
		    'index' => 'accounting.adjustments.index',
		    'create' => 'accounting.adjustments.create',
		    'store' => 'accounting.adjustments.store',
		    'show' => 'accounting.adjustments.show',
		    'edit' => 'accounting.adjustments.edit',
		    'update' => 'accounting.adjustments.update',
		    'destroy' => 'accounting.adjustments.destroy'

app/Http/Controllers/Api/ItemCategoryController.php
<?php

namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;

use Illuminate\Http\Request;
use Illuminate\Http\Response;

use App\Validators\ItemCategoryValidator;

use App\Http\Resources\ItemCategory as ItemCategoryResource;
use App\Http\Resources\ItemCategoryCollection;

use App\ItemCategory;

use DB;
use Auth;
use Config;
use Image;

use App\Traits\ApiResponse;

class ItemCategoryController extends Controller
{
    use ApiResponse;

    public function __construct()
    {
        $this->authorizeResource(ItemCategory::class, 'item_category');
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $user = $request->user();
        $term = $request->input('term') ?? null;
        $perPage = $request->input('per_page') ?? 10;
        $page = $request->input('page') ?? 1;

        $itemCategories = $user->company->itemCategories;

        if ($term) {
            $itemCategories = $itemCategories->reject(function ($element) use ($term) {
                return mb_strpos(strtolower($element->name), strtolower($term)) === false && mb_strpos(strtolower($element->description), strtolower($term)) === false;
            })->values();
        }

        $paginateData = $itemCategories->paginate($perPage);
        $collection = new ItemCategoryCollection($paginateData->getCollection());
        $metaInfo = $paginateData->toArray();
        unset($metaInfo['data']);

        return $this->successResponse(['data' => $collection, 'meta' => $metaInfo]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request, ItemCategoryValidator $itemCategoryValidator)
    {
        try {
            DB::beginTransaction();
            $input = $request->all();

            if (!$itemCategoryValidator->with($input)->passes()) {
                return $this->failResponse([
                    "message" => $itemCategoryValidator->getErrors()[0],
                    "messages" => $itemCategoryValidator->getErrors(),
                ], 422);
            }

            $user = $request->user();

            $data = [
                'name' => $input['name'],
                'description' => $input['description'],
                'user_id' => $user->id
            ];            

            if (isset($input['image']) && $input['image'])  {
                $filename = $user->id.'-item-'.substr( md5( $user->id . '-' . time() ), 0, 15) . '.jpg';
                $dir = public_path("storage/item-categories");
                $path = $dir."/".$filename;
                
                if( !\File::isDirectory($dir) ) { 
                    \File::makeDirectory($dir, 493, true);
                }
                
                $itemImgInstance = Image::make($input['image']);
                $itemImgInstance->orientate()->save($path);

                $data['image'] = $filename;
                
            }

            $itemCategory = $user->company->itemCategories()->create($data);

            DB::commit();

            return $this->successResponse([
                'data' => new ItemCategoryResource($itemCategory),
                'message' => trans('messages.item_category_created')
            ]);

        } catch (\Exception $e) {
            DB::rollback();
            return $this->failResponse([
                "message" => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ItemCategory  $itemCategory
     * @return \Illuminate\Http\Response
     */
    public function show(ItemCategory $itemCategory)
    {
        return $this->successResponse(['data' => new ItemCategoryResource($itemCategory)]);
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ItemCategory  $itemCategory
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, ItemCategory $itemCategory)
    {
        try {
            DB::beginTransaction();
            $input = $request->all();
            $itemCategoryValidator = new ItemCategoryValidator('update', $itemCategory);
            
            if (!$itemCategoryValidator->with($input)->passes()) {
                return $this->failResponse([
                    "message" => $itemCategoryValidator->getErrors()[0],
                    "messages" => $itemCategoryValidator->getErrors(),
                ], 422);
            }

            $user = $request->user();

            $data = [
                'name' => $input['name'],
                'description' => $input['description']
            ];

            if (isset($input['image']) && $input['image'])  {
                $filename = $user->id.'-item-'.substr( md5( $user->id . '-' . time() ), 0, 15) . '.jpg';
                $dir = public_path("storage/item-categories");
                $path = $dir."/".$filename;

                if( !\File::isDirectory($dir) ) { 
                    \File::makeDirectory($dir, 493, true);
                }
                
                $itemImgInstance = Image::make($input['image']);
                /*if ($itemImgInstance->height() > 300) {
                    $itemImgInstance->fit(300)->save($path);
                } else {
                }*/
                $itemImgInstance->orientate()->save($path);
                
                $data['image'] = $filename;
            }

            $itemCategory->update($data);

            DB::commit();

            return $this->successResponse([
                'data' => new ItemCategoryResource($itemCategory),
                'message' => trans('messages.item_category_updated')
            ]);

        } catch (\Exception $e) {
            DB::rollback();
            return $this->failResponse([
                "message" => $e->getMessage(),
            ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ItemCategory  $itemCategory
     * @return \Illuminate\Http\Response
     */
    public function destroy(Request $request, ItemCategory $itemCategory)
    {
        try {
            $itemCategory->delete();
            return $this->successResponse([
                'message' => trans('messages.item_category_deleted')
            ]);

        } catch (\Exception $e) {
            return $this->failResponse([
                "message" => $e->getMessage(),
            ], 500);
        } 
    }
}

resources/views/item-categories/create.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.create').' '.trans('labels.item_category'))

@section('content')
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.new').' '.__('labels.item_category') }}</h2>
        <form method="POST" action="{{ route('item-categories.store') }}" id="add-edit-item-category-form" enctype="multipart/form-data">
            @csrf
            <div class="default-form add-new-contact-form">
                <div class="generate-invoice">
                    <div class="add-form row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">{{ __('labels.name') }} <span>*</span></label>
                                <input class="form-control" type="text" name="name" placeholder="{{ __('labels.category_name') }}" required value="{{ old('name') }}" autocomplete="off" />
                                @error('name')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>                        
                            <div class="form-group">
                                <label for="description">{{ __('labels.description') }}</label>
                                <textarea class="form-control" name="description" placeholder="{{ __('labels.category_description') }}" autocomplete="off">{{ old('description', null) }}</textarea>
                                @error('description')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group prduct-pic">
                                <div class="form-group file-input file-input-large">
                                    <label for="image" id="image-preview-label">
                                        <i class="fa fa-file-image-o image-icon" aria-hidden="true"></i>
                                        {{ __('labels.icon') }}
                                    </label>
                                    <img src="" id="image-preview" style="display:none" />                            
                                    <input type="file" id="item-image" name="image" class="file-upload-preview" accept="image/*" data-img_id="image-preview" data-msg-accept="{{ __('messages.invalid_image_file_error') }}" data-label_id="image-preview-label">
                                    <a class="upload-button" data-preview_section="item-image"><i class="fa fa-pencil" aria-hidden="true"></i> {{ __('labels.edit') }}</a>
                                    @error('image')
                                        <span class="error" role="alert">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>                            
                        </div>
                    </div>
                </div>
            </div>
            <div class="comments-section">
                    <div class="form-group popup-btns">
                        <a href="{{ route('item-categories.index') }}"><button type="button" name="cancel" class="btn-custom cancel-btn">{{ __('labels.cancel') }}</button></a>
                        <button type="submit" name="submit" class="btn-custom">{{ __('labels.save') }}</button>
                    </div>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>
</div>
@endsection

resources/views/item-categories/edit.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.edit').' '.trans('labels.item_category'))

@section('content')
<div class="dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.update').' '.__('labels.item_category') }}</h2>
        {{ Form::open(array('method'=>'PUT','route' => ['item-categories.update', $itemCategory], 'id' => 'add-edit-item-category-form', 'enctype' => 'multipart/form-data')) }}
            <div class="default-form add-new-contact-form">
                <div class="generate-invoice">
                    <div class="add-form row">
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group">
                                <label for="name">{{ __('labels.name') }} <span>*</span></label>
                                <input class="form-control" type="text" name="name" placeholder="{{ __('labels.category_name') }}" required value="{{ old('name', $itemCategory->name) }}" autocomplete="off" />
                                @error('name')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>
                            <div class="form-group">
                                <label for="description">{{ __('labels.description') }}</label>
                                <textarea class="form-control" name="description" placeholder="{{ __('labels.category_description') }}" autocomplete="off">{{ old('description', $itemCategory->description) }}</textarea>
                                @error('description')
                                    <span class="error" role="alert">{{ $message }}</span>
                                @enderror
                            </div>
                        </div>
                        <div class="col-lg-6 col-md-6">
                            <div class="form-group prduct-pic">
                                <div class="form-group file-input file-input-large">
                                    @if(!$itemCategory->image)
                                    <label for="image" id="image-preview-label"><i class="fa fa-file-image-o image-icon" aria-hidden="true"></i>{{ __('labels.icon') }}</label>
                                    @endif

                                    @if($itemCategory->image)
                                        <img src="{{ URL::asset($itemCategory->image_url) }}" alt="{{ $itemCategory->name }}" id="image-preview" />
                                    @else 
                                        <img src="" id="image-preview" style="display:none" />
                                    @endif
                                    <input type="file" id="item-image" name="image" class="file-upload-preview" accept="image/*" data-img_id="image-preview" data-msg-accept="{{ __('messages.invalid_image_file_error') }}" data-label_id="image-preview-label">
                                    <a class="upload-button" data-preview_section="item-image"><i class="fa fa-pencil" aria-hidden="true"></i> {{ __('labels.edit') }}</a>
                                    @error('image')
                                        <span class="error" role="alert">{{ $message }}</span>
                                    @enderror
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </div>
            <div class="comments-section">
                    <div class="form-group popup-btns">
                        <a href="{{ route('item-categories.index') }}"><button type="button" name="cancel" class="btn-custom cancel-btn">{{ __('labels.cancel') }}</button></a>
                        <button type="submit" name="submit" class="btn-custom">{{ __('labels.update') }}</button>
                    </div>
            </div>
        </form>
    </div>
</div>
<div class="clearfix"></div>
</div>
@endsection

resources/views/item-categories/index.blade.php
@extends('layouts.dashboard')

@section('title', trans('labels.item_categories'))

@section('content')
<div class="dashboard-right cust-dashboard-md-right cust-client-dashboard-right">
    <div class="menu-icon">
        <i class="fa fa-bars" aria-hidden="true"></i>
    </div>
    <div class="invoice-container">
        <h2>{{ __('labels.item_categories') }}</h2>
        <div class="custom-tooltip"><span class="help-icon"><i class="fa fa-question-circle" aria-hidden="true"></i>
            </span>
            <span class="tooltiptext">{{ __('labels.if_you_need_help_creating_an').' '.__('labels.item_category') }}.</span>
        </div>
        <div class="invoice-btns invoice-btns-position">
            <a href="{{ route('import_resource', ['resource' => 'item-categories']) }}" class="btn-custom outline-btn"><i class="fa fa-upload" aria-hidden="true"></i> {{ __('labels.import_from_excel') }}</a>
            <a href="{{ route('export_resource', ['resource' => 'item-categories']) }}" class="btn-custom outline-btn"><i class="fa fa-download" aria-hidden="true"></i> {{ __('labels.export') }}</a>
            <a href="{{ route('item-categories.create') }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('labels.new').' '.__('labels.item_category') }}</a>
        </div>
        <div class="tabs-custom">
            <div class="tab-content">
                <div class="tab-pane active">
                    <div class="list-table-custom  products-table">
                        <table class="table table-striped" id="item-categories-list-table">
                            <thead>
                                <tr>
                                    <th>{{ __('labels.name') }}</th>
                                    <th>{{ __('labels.description') }}</th>
                                    <th>{{ __('labels.actions') }}</th>
                                </tr>
                            </thead>
                            <tbody>
                            @forelse ($itemCategories as $category)
                                <tr>
                                    <td>{{ $category->name }}</td>
                                    <td>{{ showIfAvailable($category->description) }}</td>
                                    <td class="to-show">
                                    <div class="inner-to-show">
                                        <i class="fa fa-sort-desc action-btn" class="dropdown-toggle" data-toggle="dropdown"></i>
                                        <div class="dropdown-menu">
                                            <ul>
                                                <li><a href="{{route('item-categories.edit', $category)}}">{{ __('labels.edit') }}</a></li>
                                                <li><a class="delete_resource" data-resource="{{ 'destroy-category-form-' . $category->id }}" href="{{route('item-categories.destroy', $category)}}">{{ __('labels.delete') }}</a></li>
                                                {{ Form::open(array('method'=>'DELETE','route' => ['item-categories.destroy', $category], 'id' => "destroy-category-form-{$category->id}", 'style' => 'display: none')) }}
                                                {!! Form::close() !!}
                                            </ul>
                                        </div>
</div>
                                    </td>
                                </tr>
                            @empty
                            <tr class="no-data-row">
                                <td colspan="7" rowspan="2" align="center">
                                    <div class="message"><p>{{ __('labels.you_have_not_yet_created').' '.__('labels.category') }}!</p></div>
                                    <div class="invoice-btns">
                                        <a href="{{ route('item-categories.create') }}" class="btn-custom"><i class="fa fa-plus" aria-hidden="true"></i> {{ __('labels.new').' '.__('labels.item_category') }}</a>
                                    </div>
                                </td>
                            </tr>
                            @endforelse                                
                            </tbody>
                            <tfoot>
                            </tfoot>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="clearfix"></div>
@endsection